export const fetchDataTable = () => {
  return [
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
    {
      id: "728ed52f",
      amount: 100,
      status: "pending",
      email: "m@example.com",
    },
    {
      id: "489e1d42",
      amount: 125,
      status: "processing",
      email: "example@gmail.com",
    },
    {
      id: "a3b8d425",
      amount: 150,
      status: "completed",
      email: "test1@example.com",
    },
    {
      id: "f4c2f5d4",
      amount: 175,
      status: "failed",
      email: "test2@example.com",
    },
    {
      id: "15b9c5a2",
      amount: 200,
      status: "pending",
      email: "test3@example.com",
    },
    {
      id: "af3c1f3d",
      amount: 225,
      status: "processing",
      email: "test4@example.com",
    },
    {
      id: "3d19b33f",
      amount: 250,
      status: "completed",
      email: "test5@example.com",
    },
  ];
};
